version: 2

sources:

   -  name: source_adw
      description: This is a replica of de Adventureworks database version from Indicium.
      schema: source_adw
      tables:

         -  name: salesorderheader
            description: 'General sales order information'
            columns:
               -  name: salesorderid
                  description: 'Order identification number, PK'
                  tests:
                    - unique
                    - not_null
               -  name: subtotal
                  description: 'SUM(Salesorderdetail.linetotal)'
               -  name: taxamt
                  description: 'Tax amount'
               -  name: freight
                  description: 'Shipping cost'
               -  name: totaldue
                  description: 'Total due from customer (subtotal + taxamt + freight)'
               -  name: orderdate
                  description: 'Dates the sales order was created'
               -  name: duedate
                  description: 'Date the order is due to the customer'
               -  name: orderdate
                  description: 'Date the order was shipped to the customer'
               -  name: shipmethodid
                  description: 'Shipping method, FK to shipmethod.shipmethodidid'
                  tests:
                    - not_null
               -  name: status
                  description: 'Order current status 1.In process 2.Approved; 3.Backordered; 4.Rejected; 5.Shipped; 6.Cancelled'
               -  name: onlineorderflag
                  description: '0.Order placed by sales person 1.Order placed online by customer'
               -  name: salespersonid
                  description: 'Sales person who created the sales order, FK to SalesPerson.BusinessEntityID'
                  tests:
                    - not_null
               -  name: customerid
                  description: 'Customer identification number, FK to customer.businessentityid.identity'
                  tests:
                    - not_null
               -  name: shiptoaddressid
                  description: 'Customer shipping address, FK to address.addressid'
                  tests:
                    - not_null
               -  name: creditcardid
                  description: 'Credit card identification number, FK to creditcard.creditcardid'
                  tests:
                    - not_null

         -  name: salesorderdetail
            description: 'Details of individual products associated with each sales order in salesorderheader'
            columns:
               -  name: salesorderid
                  description: 'Order identification number, FK to salesordereader.salesorderid'
                  tests:
                    - not_null
               -  name: salesorderdetailid
                  description: 'Order detail identification number, PK'
                  tests:
                    - unique
                    - not_null
               -  name: orderqty
                  description: 'Quantity of product ordered'
               -  name: productid
                  description: 'Identifition number of the product sold, FK to product.productid'
                  tests:
                    - not_null
               -  name: unitprice
                  description: 'Selling price per unit'
               -  name: unitpricediscount
                  description: 'Discount'

         -  name: salesorderheadersalesreason
            description: 'Cross-reference table connecting sales orders to sales reason codes'
            columns:
               -  name: salesorderid
                  description: 'Order identification number, FK  to salesorderheader.orderid'
                  tests:
                     - not_null
               -  name: salesreasonid
                  description: 'Sales reason identification number, FK to salesreason.salesreasonid'
                  tests:
                     - not_null
               -  name: modifieddate
                  description: 'Date and time the  sales reason was last updated'
                  tests:
                     - not_null

         -  name: salesreason
            description: 'Customer purchase reasons'
            columns:
               -  name: salesreasonid
                  description: 'Sales reason identification number, PK'
                  tests:
                     - unique
                     - not_null
               -  name: name
                  description: 'Sales reason description'
                  tests:
                     - not_null

         -  name: product
            description: 'Informations about products sold or used to manfacture sold products'
            columns:
               -  name: productid
                  description: 'Identifition number of the product sold, PK'
                  tests:
                     - unique
                     - not_null
               -  name: name
                  description: 'Name of the product'
                  tests:
                     - unique
               -  name: subcategory
                  description: 'Subcategory of the product'

         # -  name: 
         #    description: ''
         # -  name: 
         #    description: ''



